language: python
python: "2.7"
env:
 - TOX_ENV=py27
 - TOX_ENV=py32
 - TOX_ENV=py33
install:
 - travis_retry pip install "virtualenv<14.0.0" tox 
script: tox -e $TOX_ENV
after_success:
 - pip install coveralls
 - coveralls
